### ISSUE TITLE
Failed to download model checkpoints

### ISSUE THREAD

**Issue by jackee777** [joeljang/continual-knowledge-learning#1]
Thank you for your exceptional efforts. This repository and work are very nice.

I have an issue whereby I cannot download the model checkpoints, despite successfully downloading other zip files. The link for the model checkpoints appears to be functioning correctly. Despite attempting various solutions, I have been unable to resolve this issue that my connection is cut at the halfway point.
Is there a time restriction on accessing the link? If such a limitation exists, would it be possible to extend or provide an alternative download link?

I would greatly appreciate any advice or suggestions from individuals who may have encountered a similar problem.

**Comment by joeljang** [comment]
Hello,

I just checked the link for downloading the model checkpoints and it seems
to be working fine..!!

Can you try one more time?
wget https://continual.blob.core.windows.net/ckl/modelcheckpoints_main.zip

I think the internet speed has to be fast though. Maybe that is the problem?

Please let me know!

Best,
Joel

**Comment by jackee777** [comment]
Hellow @joeljang 
Thank you for taking your time to solve my issue.
Finally, we could obtain the checkpoints by adding the "continue" option, as follows.
```wget -c https://continual.blob.core.windows.net/ckl/modelcheckpoints_main.zip```

Furthermore, what you say is indeed accurate. My internet speed is inadequate. 
To mitigate this issue, we leveraged Google Colaboratory for downloading.
